/*
* Xresources preferences to load at startup
* You can add more if you know what you're doing.
*
* These are also used by the speedwmrc file in ~/.config/speedwm-de.
* When you're done with your edits, run 'make clean install'.
* 
*      Value in .Xresources				Type     Value internally */         
ResourcePref resources[]                                            = {
       { "fonts.font",					STRING,  &font },
	   { "col.background",				STRING,  &col_background },
       { "col.titlenorm",				STRING,  &col_titlenorm },
       { "col.titlesel",				STRING,  &col_titlesel },
       { "col.titlehid",				STRING,  &col_titlehid },
       { "col.windowbordernorm",		STRING,  &col_windowbordernorm },
       { "col.windowbordersel",			STRING,  &col_windowbordersel },
       { "col.windowborderurg",			STRING,  &col_windowborderurg },
	   { "col.layout",					STRING,  &col_layout },
	   { "col.layouttext",				STRING,  &col_layouttext },
       { "col.textnorm",				STRING,  &col_textnorm },
	   { "col.textsel",					STRING,  &col_textsel },
	   { "col.tag1",					STRING,  &col_tag1 },
	   { "col.tag1_text",				STRING,  &col_tag1_text },
	   { "col.tag2",					STRING,  &col_tag2 },
	   { "col.tag2.text",				STRING,  &col_tag2_text },
	   { "col.tag3",					STRING,  &col_tag3 },
	   { "col.tag3.text",				STRING,  &col_tag3_text },
	   { "col.tag4",					STRING,  &col_tag4 },
	   { "col.tag4.text",				STRING,  &col_tag4_text },
	   { "col.tag5",					STRING,  &col_tag5 },
	   { "col.tag5.text",				STRING,  &col_tag5_text },
	   { "col.tag6",					STRING,  &col_tag6 },
	   { "col.tag6.text",				STRING,  &col_tag6_text },
	   { "col.tag7",					STRING,  &col_tag7 },
	   { "col.tag7.text",				STRING,  &col_tag7_text },
	   { "col.tag8",					STRING,  &col_tag8 },
	   { "col.tag8.text",				STRING,  &col_tag8_text },
	   { "col.tag9",					STRING,  &col_tag9 },
	   { "col.tag9.text",				STRING,  &col_tag9_text },
	   { "col.tagurgent",				STRING,  &col_tagurgent },
	   { "col.status0",					STRING,  &col_status0 },
	   { "col.status1",					STRING,  &col_status1 },
	   { "col.status2",					STRING,  &col_status2 },
	   { "col.status3",					STRING,  &col_status3 },
	   { "col.status4",					STRING,  &col_status4 },
	   { "col.status5",					STRING,  &col_status5 },
	   { "col.status6",					STRING,  &col_status6 },
	   { "col.status7",					STRING,  &col_status7 },
	   { "col.status8",					STRING,  &col_status8 },
	   { "col.status9",					STRING,  &col_status9 },
	   { "col.status10",				STRING,  &col_status10 },
	   { "col.status11",				STRING,  &col_status11 },
	   { "col.status12",				STRING,  &col_status12 },
	   { "col.status13",				STRING,  &col_status13 },
	   { "col.status14",				STRING,  &col_status14 },
	   { "col.status15",				STRING,  &col_status15 },
	   { "col.powerline0_text",			STRING,  &col_powerline0_text },
	   { "col.powerline1_text",			STRING,  &col_powerline1_text },
	   { "col.powerline2_text",			STRING,  &col_powerline2_text },
	   { "col.powerline3_text",			STRING,  &col_powerline3_text },
	   { "col.powerline4_text",			STRING,  &col_powerline4_text },
	   { "col.powerline5_text",			STRING,  &col_powerline5_text },
	   { "col.powerline6_text",			STRING,  &col_powerline6_text },
	   { "col.powerline7_text",			STRING,  &col_powerline7_text },
	   { "col.systray",				    STRING,  &col_systray },
	   { "run.shell",                   STRING,  &shell },
       { "status.defaultstatus",        STRING,  &defaultstatus },
       { "fullscreen.lockfullscreen",   INTEGER, &lockfullscreen },
	   { "fullscreen.movefullscreenmon",INTEGER, &movefullscreenmon },
	   { "fullscreen.hidebar",		    INTEGER, &fullscreenhidebar },
	   { "rule.refresh",				INTEGER, &refreshrules },
	   { "border.size",				    INTEGER, &bordersize }, 
       { "stack.snap",				    INTEGER, &snap },
       { "bar.hide",					INTEGER, &hidebar },
       { "stack.mastercount",           INTEGER, &mastercount },
	   { "stack.attachdirection",       INTEGER, &attachdirection },
       { "tiling.resizehints",          INTEGER, &resizehints },
       { "tag.start",					INTEGER, &startontag },
	   { "client.decorhints",           INTEGER, &decorhints },
       { "client.swallow",				INTEGER, &swallowclients },
       { "client.swallowfloating",      INTEGER, &swallowfloating },
	   { "bar.height",					INTEGER, &barheight },
	   { "bar.paddingv",				INTEGER, &barpaddingv },
	   { "bar.paddingh",				INTEGER, &barpaddingh },
	   { "stack.centerfloating",        INTEGER, &centerfloating },
	   { "client.savefloat",			INTEGER, &savefloat },
	   { "cursor.warp",					INTEGER, &warpcursor },
	   { "tag.pertag",					INTEGER, &pertag },
	   { "stack.i3mcount",				INTEGER, &i3mastercount },
	   { "bar.titleposition",			INTEGER, &titleposition },
	   { "bar.hide.layout",			    INTEGER, &hidelayout },
	   { "bar.hide.title",	            INTEGER, &hidetitle },
	   { "bar.hide.icon",			    INTEGER, &hideicon },
	   { "bar.hide.tags",				INTEGER, &hidetags },
	   { "bar.hide.emptytags",			INTEGER, &hideemptytags },
	   { "bar.hide.status",				INTEGER, &hidestatus },
	   { "bar.hide.systray",            INTEGER, &hidesystray },
	   { "bar.hide.sticky",				INTEGER, &hidesticky },
	   { "bar.hide.floating",			INTEGER, &hidefloating },
       { "bar.hide.clientindicator",    INTEGER, &hideclientindicator },
	   { "bar.powerline.tag.shape",     INTEGER, &tagplshape },
	   { "client.hide.border",			INTEGER, &hideborder },
	   { "client.hide.singleborder",	INTEGER, &hidesingleborder },
	   { "client.allowurgent",			INTEGER, &allowurgent },
	   { "tag.resetlayout",				INTEGER, &resetlayout },
	   { "tag.resetmfact",			    INTEGER, &resetmfact },
	   { "tag.resetgaps",			    INTEGER, &resetgaps },
	   { "client.wmclass",		        INTEGER, &wmclass },
	   { "mouse.clicktofocus",			INTEGER, &clicktofocus },
	   { "tag.urgentwindows",			INTEGER, &urgentwindows },
	   { "tag.underline",				INTEGER, &underline },
	   { "tag.underlinepad",			INTEGER, &underlinepad },
	   { "tag.underlinestroke",			INTEGER, &underlinestroke },
	   { "tag.underlinevoffset",		INTEGER, &underlinevoffset },
	   { "gaps.enable",				    INTEGER, &enablegaps },
	   { "gaps.sizeih",					INTEGER, &gapsizeih },
	   { "gaps.sizeiv",					INTEGER, &gapsizeiv },
	   { "gaps.sizeoh",					INTEGER, &gapsizeoh },
	   { "gaps.sizeov",					INTEGER, &gapsizeov },
	   { "gaps.smartgaps",				INTEGER, &smartgaps },
	   { "gaps.smartgapsize",			INTEGER, &smartgapsize },
	   { "mouse.mfact",					INTEGER, &mousemfact },
	   { "mouse.cfact",					INTEGER, &mousecfact },
	   { "focus.spawned",				INTEGER, &focusspawn },
	   { "client.floatscratchpad",      INTEGER, &floatscratchpad },
	   { "client.autofocus",            INTEGER, &autofocus },
	   { "client.automove",             INTEGER, &automove },
	   { "client.autoresize",           INTEGER, &autoresize },
	   { "mfact",						FLOAT,   &mfact },
       { "mfact.lowest",				FLOAT,   &lowestmfact },
	   { "switcher.menupositionv",		INTEGER, &menupositionv },
	   { "switcher.menupositionh",		INTEGER, &menupositionh },
	   { "switcher.maxwidth",			INTEGER, &maxwidth },
	   { "switcher.maxheight",			INTEGER, &maxheight },
	   { "color.selectedtitle",			INTEGER, &colorselectedtitle },
	   { "color.hiddentitle",			INTEGER, &colorhiddentitle },
	   { "color.layout",				INTEGER, &colorlayout },
#if USESYSTRAY
	   { "systray.pinning",				INTEGER, &systraypinning },
	   { "systray.position",			INTEGER, &systrayposition },
	   { "systray.padding",				INTEGER, &systrayspacing },
#endif
       { "layout.monocle.format",       STRING,  &monocleformat },
	   { "layout.monocle.clientcount",	INTEGER, &monocleclientcount },
	   { "layout.monocle.count",        INTEGER, &monoclecount },
	   { "layout.deck.format",          STRING,  &deckformat },
	   { "layout.deck.count",		    INTEGER, &deckcount },
#if USEWINICON
       { "icon.size",					INTEGER, &iconsize },
       { "icon.spacing",				INTEGER, &iconspacing },
#endif
#if USETAGPREVIEW
	   { "tag.preview.scale",			INTEGER, &scalepreview },
	   { "tag.preview",					INTEGER, &tagpreview },
	   { "tag.preview.paddingv",		INTEGER, &tagpreviewpaddingv },
	   { "tag.preview.paddingh",		INTEGER, &tagpreviewpaddingh },
	   { "tag.preview.bar",			    INTEGER, &barpreview },
#endif
	   { "bar.position",				INTEGER, &barposition },
#if USEFADE
	   { "client.fade.inactive",	    INTEGER, &fadeinactive },
	   { "client.fade.windows",	        INTEGER, &fadewindows },
#endif
#if USEROUNDCORNERS
	   { "border.roundedcorners",		INTEGER, &roundedcorners },
	   { "border.cornerradius",			INTEGER, &cornerradius },
#endif
       /* Traditional color system support (for example useful for Pywal) */
	   { "color0",					    STRING,  &col_background },
	   { "color0",						STRING,  &col_systray },
	   { "color0",						STRING,  &col_titlenorm },
       { "color4",						STRING,  &col_titlesel },
       { "color0",						STRING,  &col_titlehid },
	   { "color8",						STRING,  &col_windowbordersel },
	   { "color0",						STRING,  &col_windowbordernorm },
	   { "color4",						STRING,  &col_textnorm },
	   { "color0",						STRING,  &col_textsel },
	   { "color0",						STRING,  &col_layouttext },
	   { "color2",						STRING,  &col_layout },
	   { "color1",						STRING,  &col_tag1 },
	   { "color0",						STRING,  &col_tag1_text },
       { "color2",						STRING,  &col_tag2 },
	   { "color0",						STRING,  &col_tag2_text },
	   { "color3",						STRING,  &col_tag3 },
	   { "color0",						STRING,  &col_tag3_text },
	   { "color4",						STRING,  &col_tag4 },
	   { "color0",						STRING,  &col_tag4_text },
	   { "color5",						STRING,  &col_tag5 },
       { "color0",						STRING,  &col_tag5_text },
	   { "color6",						STRING,  &col_tag6 },
       { "color0",						STRING,  &col_tag6_text },
       { "color7",						STRING,  &col_tag7 },
	   { "color0",						STRING,  &col_tag7_text },
	   { "color8",						STRING,  &col_tag8 },
	   { "color0",						STRING,  &col_tag8_text },
	   { "color9",						STRING,  &col_tag9 },
	   { "color0",						STRING,  &col_tag9_text },
	   { "color0",						STRING,  &col_status0 },
	   { "color1",						STRING,  &col_status1 },
	   { "color2",						STRING,  &col_status2 },
	   { "color3",						STRING,  &col_status3 },
	   { "color4",						STRING,  &col_status4 },
	   { "color5",						STRING,  &col_status5 },
	   { "color6",						STRING,  &col_status6 },
	   { "color7",						STRING,  &col_status7 },
	   { "color8",						STRING,  &col_status8 },
	   { "color9",						STRING,  &col_status9 },
	   { "color10",						STRING,  &col_status10 },
	   { "color11",						STRING,  &col_status11 },
	   { "color12",						STRING,  &col_status12 },
	   { "color13",						STRING,  &col_status13 },
	   { "color14",						STRING,  &col_status14 },
	   { "color15",						STRING,  &col_status15 },
	   { "color0",						STRING,  &col_powerline0 },
	   { "color1",						STRING,  &col_powerline1 },
	   { "color2",						STRING,  &col_powerline2 },
	   { "color3",						STRING,  &col_powerline3 },
	   { "color4",						STRING,  &col_powerline4 },
	   { "color5",						STRING,  &col_powerline5 },
	   { "color6",						STRING,  &col_powerline6 },
	   { "color7",						STRING,  &col_powerline7 },
	   { "color4",						STRING,  &col_powerline0_text },
	   { "color0",						STRING,  &col_powerline1_text },
	   { "color0",						STRING,  &col_powerline2_text },
	   { "color0",						STRING,  &col_powerline3_text },
	   { "color0",						STRING,  &col_powerline4_text },
	   { "color0",						STRING,  &col_powerline5_text },
	   { "color0",						STRING,  &col_powerline6_text },
	   { "color0",						STRING,  &col_powerline7_text },
/*       value in .Xresources           type     value in speedwm */
};
